Main:
  Sounds Enabled: true
  Hologram in front: false
  Upgrade By Smelting Materials: true
  Upgrade With Economy: true
  Upgrade With XP: true
  Level Cost Multiplier: 50
  Remember Furnace Item Levels: true
  Furnaces Have Holograms: true
  Redstone Deactivates Furnaces: true
  Furnace Upgrade Cost: IRON_INGOT
  Use Custom Recipes: true
  No Rewards From Custom Recipes: true
  Upgrade Particle Type: SPELL_WITCH
  Access Furnaces Remotely: true
  Furnace Tick Speed: 10
  Auto Save Interval In Seconds: 15
  Overheat Particles: true
Interfaces:
  Reward Icon: GOLDEN_APPLE
  Performance Icon: REDSTONE
  FuelShare Icon: COAL_BLOCK
  FuelDuration Icon: COAL
  Overheat Icon: FIRE_CHARGE
  Economy Icon: SUNFLOWER
  XP Icon: EXPERIENCE_BOTTLE
  Glass Type 1: 7
  Glass Type 2: 11
  Glass Type 3: 3
  Replace Glass Type 1 With Rainbow Glass: false
Database:
  Activate Mysql Support: false
  IP: 127.0.0.1
  Port: 3306
  Database Name: EpicFurnaces
  Prefix: EF-
  Username: PUT_USERNAME_HERE
  Password: PUT_PASSWORD_HERE
System:
  Download Needed Data Files: true
  Language Mode: en_US
  Debugger Enabled: false
settings:
  levels:
    Level-1:
      Performance: 10%
      Reward: 10%:1
      Cost-xp: 20
      Cost-eco: 5000
    Level-2:
      Performance: 25%
      Reward: 20%:1-2
      Cost-xp: 25
      Cost-eco: 7500
    Level-3:
      Performance: 40%
      Reward: 35%:2-3
      Fuel-duration: 10%
      Cost-xp: 30
      Cost-eco: 10000
    Level-4:
      Performance: 55%
      Reward: 50%:2-4
      Fuel-duration: 25%
      Cost-xp: 35
      Cost-eco: 12000
    Level-5:
      Performance: 75%
      Reward: 70%:3-4
      Fuel-duration: 45%
      Overheat: 1
      Cost-xp: 40
      Cost-eco: 15000
    Level-6:
      Performance: 75%
      Reward: 70%:3-4
      Fuel-duration: 45%
      Overheat: 2
      Fuel-share: 1
      Cost-xp: 40
      Cost-eco: 15000