name: EpicFurnaces
version: ${project.version}
main: com.songoda.epicfurnaces.EpicFurnaces
authors: [Brianna, GB6]
website: https://songoda.com/
depend: [HolographicDisplays, Vault]
softdepend: [PlotSquared, GriefPrevention, USkyBlock, SkyBlock, WorldGuard, Factions]
commands:
  epicfurnaces:
    description: Default command for the EpicFurnaces plugin.
    default: true
    aliases: [ef]
    usage: /<command> [reload]