name: EpicFurnaces
version: maven-version-number
main: com.songoda.epicfurnaces.EpicFurnaces
authors: [Brianna, GB6]
website: https://songoda.com/
depend: [Vault]
softdepend: [PlotSquared, GriefPrevention, USkyBlock, SkyBlock, WorldGuard, Factions, HolographicDisplays, FabledSkyBlock]
commands:
  epicfurnaces:
    description: Default command for the EpicFurnaces plugin.
    default: true
    aliases: [ef]
    usage: /<command> [reload]